name: rush
description: Rush is a powerful and flexible library for Flutter that accelerates UI development
version: 0.1.0
homepage: https://pawan.app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
